steps:
  # Build the container image
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "--tag=gcr.io/$PROJECT_ID/$BUILD_ID",
        '--build-arg="CLOUD_SQL_INSTANCE=$_CLOUD_SQL_INSTANCE"',
        ".",
      ]

  # Push the container image to Container Registry
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/$BUILD_ID"]

  # Deploy image
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: "gcloud"
    args:
      [
        "run",
        "deploy",
        "$_CLOUD_RUN_SERVICE",
        "--image",
        "gcr.io/$PROJECT_ID/$BUILD_ID",
        "--region=us-central1",
      ]
images:
  - gcr.io/$PROJECT_ID/$BUILD_ID
