name: cloudrun-deploy
on:
  push:
    branches:
      - "main"
jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    env:
      # Tag for the docker build image
      BUILD_TAG: gcr.io/prismatic-age-287921/prod-big-air
      # Cloud sql instance for cloud sql proxy to connect to inside in the container
      CLOUD_SQL_INSTANCE: prismatic-age-287921:us-central1:data-big-air
      # Instance of the cloud run to deploy to
      CLOUD_RUN_INSTANCE: prod-big-air
      # Cloud project ID
      GCP_PROJECT_ID: prismatic-age-287921
    steps:
      - name: Checkout
        uses: actions/checkout@master

      # Decode base64 env string to .env.production file for nextjs to consume
      - name: Create env file
        env:
          ENV_FILE: ${{ secrets.ENV_FILE }}
        run: |
          echo $ENV_FILE | base64 --decode > .env.production

      # Setup gcloud CLI
      - name: Set up Cloud auth
        uses: "google-github-actions/auth@v0"
        with:
          credentials_json: "${{ secrets.GCP_CREDENTIALS }}"

      - name: Set up Cloud SDK
        uses: "google-github-actions/setup-gcloud@v0"

      # Configure Docker with Credentials
      - name: Configure Docker
        run: |
          gcloud auth configure-docker

      # Build and publish the image
      - name: Build & Publish
        run: |
          gcloud config set project $GCP_PROJECT_ID
          gcloud builds submit --config=cloudbuild.yaml \
          --substitutions=_CLOUD_SQL_INSTANCE=$CLOUD_SQL_INSTANCE,_TAG=$BUILD_TAG
          gcloud config set run/region us-central1

      # Deploy the Docker image to the cloud run instance
      - name: Deploy
        run: |
          gcloud run deploy $CLOUD_RUN_INSTANCE --image $BUILD_TAG
